openapi: 3.0.0
info:
  title: Microservices API
  version: 1.0.0
  description: A combined API for Comments, Users, and Posts services.

servers:
  - url: http://localhost
    description: Local Environment

paths:
  /users:
    get:
      summary: Get a list of users with pagination
      operationId: getUsers
      tags:
        - Users
      parameters:
        - name: page
          in: query
          description: The page number to retrieve
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: The number of users to return per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: A list of users with pagination information
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
                  hasMore:
                    type: boolean
                    description: Indicates whether there are more users to fetch
                    example: true
        "400":
          description: Invalid query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid page or limit parameter"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to fetch public profiles"
    post:
      summary: User registration
      operationId: registerUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        "400":
          description: Invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    message: "Email and password are required"
                invalidEmail:
                  summary: Invalid email format
                  value:
                    message: "Invalid email format"
                weakPassword:
                  summary: Weak password
                  value:
                    message: "Password must be at least 8 characters long"

  /followers:
    post:
      summary: Add a follower
      description: Adds a follower to a user.
      operationId: addFollower
      tags:
        - followers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - follower_id
                    - followee_id
                  properties:
                    follower_id:
                      type: integer
                      example: 4
                    followee_id:
                      type: integer
                      example: 2
      responses:
        "201":
          description: Follower added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Follower added successfully"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    message: "follower_id and followee_id are required"
                invalidEmail:
                  summary: follower_id and followee_id are equal
                  value:
                    message: "Follower id and followee id must be different"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
  /users/login:
    post:
      summary: User login
      operationId: loginUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "200":
          description: Login successful
          headers:
            Set-Cookie:
              description: Sets the access token as a cookie
              schema:
                $ref: "#/components/schemas/cookie"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        "400":
          description: Invalid request

  /users/{id}/profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User profile found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid user ID"
        "404":
          description: User not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /users/{id}:
    put:
      summary: Update user details
      operationId: updateUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  message:
                    type: string
                    example: "User details updated successfully"
        "400":
          description: Invalid user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    message: "Username and email are required"
                invalidEmail:
                  summary: Invalid email format
                  value:
                    message: "Invalid email format"
                weakPassword:
                  summary: Weak password
                  value:
                    message: "Password must be at least 8 characters long"            
                
        "404":
          description: User not foun
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User with given id not found"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"

  /comments:
    post:
      summary: Add a comment
      operationId: addComment
      tags:
        - Comments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: "#/components/schemas/Comment"
      responses:
        "201":
          description: Comment created successfully
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                invalidJSON:
                  summary: Invalid JSON request
                  value:
                    message: "Invalid JSON request"
                missingFields:
                  summary: Missing required fields
                  value:
                    message: "Missing required fields"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Failed to add comment"

  /comments/{id}:
    get:
      summary: Get comments by entity ID
      description: Fetch comments and replies for a specific entity, optionally filtered by user ID.
      parameters:
        - name: id
          in: path
          description: The ID of the entity for which to fetch comments.
          required: true
          schema:
            type: integer
            example: 123
        - name: target_id
          in: query
          description: The ID of the user to filter comments by (optional).
          required: false
          schema:
            type: integer
            example: 456
        - name: page
          in: query
          description: The page number for pagination (optional).
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          description: The number of comments per page (optional).
          required: false
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: Successfully retrieved comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 123
                        entity_id:
                          type: integer
                          example: 123
                        entity_type:
                          type: string
                          example: "post"
                        author_id:
                          type: integer
                          example: 456
                        replies_count:
                          type: integer
                          example: 456
                        content:
                          type: string
                          example: "This is a comment"
                        created_at:
                          type: string
                          format: date-time
                          example: "2023-08-26T12:00:00Z"
                        reactions:
                          type: string
                          format: json
                          example: '{"like": 10, "dislike": 2}'    
                  hasMore:
                    type: boolean
                    example: true
        '400':
          description: Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "invalid entity ID"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "failed to get comments: [error details]"

  /posts/{postId}:
    get:
      summary: Get post details
      operationId: getPost
      tags:
        - Posts
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Post found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Post not found

components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UpdateUserRequest:
      type: object
      required:
        - email
        - username
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        bio:
          type: string
        profile_pic:
          type: string
          format: uri

    cookie:
      type: string
      example: access_token=abcde12345; Path=/; HttpOnly

    Comment:
      type: object
      required:
        - entity_id
        - entity_type
        - content
        - author_id
      properties:
        entity_id:
          type: string
          description: The ID of the entity being commented on (e.g., post ID)
        entity_type:
          type: string
          enum: ["post", "comment"]
          description: The type of entity being commented on
        content:
          type: string
          description: The text content of the comment
        author_id:
          type: string
          description: The ID of the author of the comment

    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          nullable: true
        email:
          type: string
        status:
          type: string
          enum: ["active", "inactive", "banned"]
        role:
          type: string
          enum: ["user", "admin", "moderator"]
        first_name:
          type: string
          nullable: true
        last_name:
          type: string
          nullable: true
        profile_pic:
          type: string
          nullable: true
          format: uri
        bio:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Post:
      type: object
      required:
        - postId
        - title
        - content
      properties:
        postId:
          type: string
        title:
          type: string
        content:
          type: string
